### ISSUE TITLE
OSError: [Errno 5] EIO

### ISSUE THREAD

**Issue by andreasr81** [gregwa1953/SI7021-MicroPython-RPi-Pico#4]
Hi i get this Error on a Pico W

Temperature: 22.19818C
Temperature: 71.95673F
Humidity: 39.30334
Dew Point: 7.682032
bytearray(b'\x00\xe1(E2\x11HT')
Traceback (most recent call last):
  File "<stdin>", line 22, in <module>
  File "SI7021.py", line 190, in revision
OSError: [Errno 5] EIO

**Comment by gregwa1953** [comment]
Thank you for your report.
I'll check it out and get back to you.

**Comment by gregwa1953** [comment]
Try commenting out lines 20, 21, 22 and 23 and try running again.
Sometimes the board revision doesn't come in correctly.
Let me know what your results are.

**Comment by andreasr81** [comment]
okay thanks, i commented out 22,23 and it works, many thanks

**Comment by gregwa1953** [comment]
Glad it worked for you.
